### ISSUE TITLE
Filter not able to process "NOT EQUAL TO". 

### ISSUE THREAD

**Issue by hopecee** [datanucleus/datanucleus-jdo-query#7]
Hi. 
I tried to execute a code like this, and I got a stack trace.

    JDOPersistenceManager jdopm = (JDOPersistenceManager) pm;
    QProductClass cand = QProductClass.candidate();
    JDOQLTypedQuery<Product> tq = jdopm.newJDOQLTypedQuery(Product.class);
    List<Product> prods = tq.filter(cand.name.ne(value)).executeList();

The stacktrace;

    Jan 03, 2018 8:01:14 PM com.hop.tub.servlets.TuListDataServlet doPost
    SEVERE: null
    org.neo4j.graphdb.QueryExecutionException: Unknown operation '!=' (you probably meant to use '<>',   which is the operator for inequality testing) (line 1, column 95 (offset: 94))
    "START this=node:DN_TYPES(class="com.hop.tub.neo4j.jdo.model.Product") WHERE (this.name != "ampiclox") RETURN this"
                                                                                               ^
	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:84)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:369)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:359)
	at org.datanucleus.store.neo4j.Neo4jUtils.executeCypherQuery(Neo4jUtils.java:319)
	at org.datanucleus.store.neo4j[DEBUG] 2018-01-03 20:01:14.011 [qtp1955990522-86] Transaction - Transaction rolled back in 3 ms

`.eq()` works but `.ne()` does not work. Any help?

And is there any way to search if an object contains a value?

**Comment by andyjefferson** [comment]
Where is the testcase that is required? Attach it to any issue

**Comment by andyjefferson** [comment]
What does this have to do with a plugin that simply creates q classes?

**Comment by hopecee** [comment]
This is my testcase.
I have created list of product with names, with this Model;

    ...
    @PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
    long id;
    @Persistent
    private String name = null;
    ...

(1) Apple,
(2) Appleman,
(3) Orangecake,
(4) Smallorange,
(5) Orangecake,
(6) Mangocake.

Now I want to search for list of Product that is equal to a variable value.
Using;

    String  value = "Apple";
    List<Product> prods = tq.filter(cand.name.eq(value)).executeList();

Using `.eq()` equality;
When value = "Apple";  // expected result  => (1) Apple.        // works .
Using `.startsWith()` begins with;
When value = "Apple";  // expected result  => (1) Apple.        // works .
                                                                       (2) Appleman,
Using `.ne()` inequality;
When value = "Apple";  // expected result  => (2) Appleman,    //does not work, gives me the stack trace.
                                                                       (3) Orangecake,
                                                                       (4) Smallorange,
                                                                       (5) Orangecake,
                                                                       (6) Mangocake. 

I do not know how to search the Product name which contains `Apple`.

**Comment by andyjefferson** [comment]
A testcase is not text dumped into an issue, it is a zip file attached to an issue. The documentation provides a template, so use that. And as already said this is nothing to do with the datanucleus-jdo-query plugin so is in the wrong plugin. Raise a valid issue against the datanucleus-neo4j plugin WITH testcase

**Comment by hopecee** [comment]
Thanks, I thought the problem was from datanucleus-jdo-query plugin. I hope you understand the issue?

**Comment by andyjefferson** [comment]
As already said, this plugin creates q classes and that is all

**Comment by hopecee** [comment]
For the testcase which files should I include?

**Comment by andyjefferson** [comment]
Nothing to do with this plugin.
